name: PHPStan

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy config.php
        run: cp "config.sample.php" "config.php"

      - name: Run composer
        uses: php-actions/composer@v6 # or alternative dependency management

      - name: Run phpstan
        uses: php-actions/phpstan@v3
        with:
          path: src/

    # ... then your own project steps ...